/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */


import {
  BsButton as BsButton
} from './components/button/button';

declare global {
  interface HTMLBsButtonElement extends BsButton, HTMLElement {
  }
  var HTMLBsButtonElement: {
    prototype: HTMLBsButtonElement;
    new (): HTMLBsButtonElement;
  };
  interface HTMLElementTagNameMap {
    "bs-button": HTMLBsButtonElement;
  }
  interface ElementTagNameMap {
    "bs-button": HTMLBsButtonElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "bs-button": JSXElements.BsButtonAttributes;
    }
  }
  namespace JSXElements {
    export interface BsButtonAttributes extends HTMLAttributes {
      active?: boolean;
      bsBlock?: boolean;
      bsOutline?: boolean;
      bsSize?: string;
      bsType?: string;
      disabled?: boolean;
      href?: string;
    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }
